before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
